### PR TITLE
Fixed highlighting of links and inline comments

### PR DESCRIPTION
**Pull request by KGHustad**
Removed strikethrough highlighting from GFM, updated link to reflect DocOnce's syntax, and added highlighting of inline comments.

### CODE REVIEW

**Comment by dragly** [comment]
Great! Thanks for the contribution!

**Comment by Fenrihr** [comment]
Hi!! I am using Atom 1.35.1 with Atom Ligth Theme (UI + Syntax) and `language-doconce` 0.38 but the highlighting of inline comments don't work.

I also tested all the combination of UI and Syntax Theme.

**Comment by KGHustad** [comment]
The highlighting does work for me, except only the first inline comment on a single line is highlighted.

**Comment by KGHustad** [comment]
Relevant issue: #10

**Pull request merged**
